zuul:
  routes:
    actors:
      path: /actors/**
      url: https://actor-service.herokuapp.com/api/actors
    login:
      path: /login/**
      url: https://auth-microservice.herokuapp.com/api/auth
    films:
      path: /films/**
      url: http://filmsapi-dev.eu-central-1.elasticbeanstalk.com/api/Films
    favorites:
      path: /favorites/**
      url: http://usersapi-dev.eu-central-1.elasticbeanstalk.com/api/Favorites