zuul:
  routes:
    actors:
      path: /actors/**
      url: https://actor-service.herokuapp.com/api/actors
    login:
      path: /login/**
      url: https://auth-microservice.herokuapp.com/api/auth
    admin:
      path: /admin/**
      url: https://auth-microservice.herokuapp.com/api/admin
    user:
      path: /user/**
      url: https://auth-microservice.herokuapp.com/api/user
    films:
      path: /films/**
      url: http://filmsapi-dev.eu-central-1.elasticbeanstalk.com/api/Films